version: "3.9"
services:
    relay:
        image: aelzeiny/twitch-relay
        ports:
            - "9999:9999"
        volumes:
            - /dev/bus/usb/001/
        command: python controller_relay.py -p /dev/bus/usb/001/003