version: "3.9"
services:
    relay:
        build:
            context: .
        image: aelzeiny/twitch-relay
        ports:
            - "9999:9999"
        # volumes:
        #     - /dev/ttyUSB0
        command: python controller_relay.py