version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx-files/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - traffic
      - auctioneer
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  auctioneer:
    # build:
    #   context: .
    #   dockerfile: ./serverfull-auctioneer/Dockerfile
    image: aelzeiny/twitch-auctioneer
    ports:
      - "5001:5001"
    environment:
      - "JWT_SECRET=${JWT_SECRET}"
      - "TWITCH_ACCESS_TOKEN=${TWITCH_ACCESS_TOKEN}"  # needed for chatbot. See twitchtokengenerator.com
      - "TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}"
      - "TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}"
      - "TRAFFIC_INTERNAL_URL=http://traffic:8443/api"
      - "APP_EXTERNAL_URL=https://tearsofthekingdom.live"
    depends_on:
      - traffic
  traffic:
    # build:
    #   context: .
    #   dockerfile: ./traffic-controller/Dockerfile
    image: aelzeiny/twitch-traffic
    ports:
      - "8443:8443"
    depends_on:
      - kurento
    environment:
      - "PRESENTER_SUPER_SECRET=${JWT_SECRET}"
      - "KURENTO_URL=ws://kurento:8888/kurento"
  kurento:
    image: kurento/kurento-media-server:6.13
    ports:
      - "8888:8888/tcp"
      - "5000-5050:5000-5050/udp"
    environment:
      - "KMS_MIN_PORT=5000"
      - "KMS_MAX_PORT=5050"
    volumes:
      - ./kurento-files/WebRtcEndpoint.conf.ini:/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
